# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'durra/main.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_durraDialog(object):
    def setupUi(self, durraDialog):
        durraDialog.setObjectName("durraDialog")
        durraDialog.resize(952, 854)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(durraDialog.sizePolicy().hasHeightForWidth())
        durraDialog.setSizePolicy(sizePolicy)
        durraDialog.setMinimumSize(QtCore.QSize(950, 0))
        durraDialog.setToolTip("")
        durraDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(durraDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblFilename = QtWidgets.QLabel(durraDialog)
        self.lblFilename.setObjectName("lblFilename")
        self.verticalLayout_3.addWidget(self.lblFilename)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblTitle = QtWidgets.QLabel(durraDialog)
        self.lblTitle.setObjectName("lblTitle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblTitle)
        self.txtTitle = QtWidgets.QLineEdit(durraDialog)
        self.txtTitle.setReadOnly(True)
        self.txtTitle.setObjectName("txtTitle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtTitle)
        self.lblEditingTimeLabel = QtWidgets.QLabel(durraDialog)
        self.lblEditingTimeLabel.setObjectName("lblEditingTimeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblEditingTimeLabel)
        self.lblEditingTime = QtWidgets.QLabel(durraDialog)
        self.lblEditingTime.setObjectName("lblEditingTime")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblEditingTime)
        self.lblAuthor = QtWidgets.QLabel(durraDialog)
        self.lblAuthor.setObjectName("lblAuthor")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblAuthor)
        self.txtAuthorFullname = QtWidgets.QLineEdit(durraDialog)
        self.txtAuthorFullname.setReadOnly(True)
        self.txtAuthorFullname.setObjectName("txtAuthorFullname")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtAuthorFullname)
        self.lblAuthorEmail = QtWidgets.QLabel(durraDialog)
        self.lblAuthorEmail.setObjectName("lblAuthorEmail")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblAuthorEmail)
        self.txtAuthorEmail = QtWidgets.QLineEdit(durraDialog)
        self.txtAuthorEmail.setReadOnly(True)
        self.txtAuthorEmail.setObjectName("txtAuthorEmail")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtAuthorEmail)
        self.lblLicense = QtWidgets.QLabel(durraDialog)
        self.lblLicense.setObjectName("lblLicense")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblLicense)
        self.txtLicense = QtWidgets.QLineEdit(durraDialog)
        self.txtLicense.setReadOnly(True)
        self.txtLicense.setObjectName("txtLicense")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txtLicense)
        self.lblReversionLabel = QtWidgets.QLabel(durraDialog)
        self.lblReversionLabel.setObjectName("lblReversionLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lblReversionLabel)
        self.txtRevision = QtWidgets.QLineEdit(durraDialog)
        self.txtRevision.setReadOnly(True)
        self.txtRevision.setObjectName("txtRevision")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txtRevision)
        self.lblKeyword = QtWidgets.QLabel(durraDialog)
        self.lblKeyword.setObjectName("lblKeyword")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lblKeyword)
        self.txtKeyword = QtWidgets.QLineEdit(durraDialog)
        self.txtKeyword.setReadOnly(True)
        self.txtKeyword.setObjectName("txtKeyword")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.txtKeyword)
        self.lblVersionLabel = QtWidgets.QLabel(durraDialog)
        self.lblVersionLabel.setObjectName("lblVersionLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.lblVersionLabel)
        self.lblVersion = QtWidgets.QLabel(durraDialog)
        self.lblVersion.setObjectName("lblVersion")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lblVersion)
        self.txtDescription = QtWidgets.QTextEdit(durraDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDescription.sizePolicy().hasHeightForWidth())
        self.txtDescription.setSizePolicy(sizePolicy)
        self.txtDescription.setMaximumSize(QtCore.QSize(16777215, 120))
        self.txtDescription.setReadOnly(True)
        self.txtDescription.setObjectName("txtDescription")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.txtDescription)
        self.txtMessage = QtWidgets.QTextEdit(durraDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMessage.sizePolicy().hasHeightForWidth())
        self.txtMessage.setSizePolicy(sizePolicy)
        self.txtMessage.setMaximumSize(QtCore.QSize(16777215, 76))
        self.txtMessage.setSizeIncrement(QtCore.QSize(0, 0))
        self.txtMessage.setObjectName("txtMessage")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.txtMessage)
        self.txtLog = QtWidgets.QTextEdit(durraDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtLog.sizePolicy().hasHeightForWidth())
        self.txtLog.setSizePolicy(sizePolicy)
        self.txtLog.setMinimumSize(QtCore.QSize(0, 0))
        self.txtLog.setMaximumSize(QtCore.QSize(16777215, 138))
        self.txtLog.setSizeIncrement(QtCore.QSize(0, 0))
        self.txtLog.setReadOnly(True)
        self.txtLog.setObjectName("txtLog")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.txtLog)
        self.groupBox_2 = QtWidgets.QGroupBox(durraDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 76))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 168))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 921, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnCommitMetaFiles = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCommitMetaFiles.sizePolicy().hasHeightForWidth())
        self.btnCommitMetaFiles.setSizePolicy(sizePolicy)
        self.btnCommitMetaFiles.setObjectName("btnCommitMetaFiles")
        self.horizontalLayout_2.addWidget(self.btnCommitMetaFiles)
        self.btnCommit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCommit.sizePolicy().hasHeightForWidth())
        self.btnCommit.setSizePolicy(sizePolicy)
        self.btnCommit.setMouseTracking(True)
        self.btnCommit.setDefault(True)
        self.btnCommit.setObjectName("btnCommit")
        self.horizontalLayout_2.addWidget(self.btnCommit)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnNewMajorVersion = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewMajorVersion.sizePolicy().hasHeightForWidth())
        self.btnNewMajorVersion.setSizePolicy(sizePolicy)
        self.btnNewMajorVersion.setMouseTracking(True)
        self.btnNewMajorVersion.setObjectName("btnNewMajorVersion")
        self.horizontalLayout_2.addWidget(self.btnNewMajorVersion)
        self.btnNewMinjorVersion = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewMinjorVersion.sizePolicy().hasHeightForWidth())
        self.btnNewMinjorVersion.setSizePolicy(sizePolicy)
        self.btnNewMinjorVersion.setMouseTracking(True)
        self.btnNewMinjorVersion.setObjectName("btnNewMinjorVersion")
        self.horizontalLayout_2.addWidget(self.btnNewMinjorVersion)
        self.btnNewPatchedVersion = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewPatchedVersion.sizePolicy().hasHeightForWidth())
        self.btnNewPatchedVersion.setSizePolicy(sizePolicy)
        self.btnNewPatchedVersion.setMouseTracking(True)
        self.btnNewPatchedVersion.setObjectName("btnNewPatchedVersion")
        self.horizontalLayout_2.addWidget(self.btnNewPatchedVersion)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.SpanningRole, self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(durraDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 64))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 246))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 19, 911, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSave = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnGenFiles = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGenFiles.sizePolicy().hasHeightForWidth())
        self.btnGenFiles.setSizePolicy(sizePolicy)
        self.btnGenFiles.setObjectName("btnGenFiles")
        self.horizontalLayout.addWidget(self.btnGenFiles)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnInitGit = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInitGit.sizePolicy().hasHeightForWidth())
        self.btnInitGit.setSizePolicy(sizePolicy)
        self.btnInitGit.setObjectName("btnInitGit")
        self.horizontalLayout.addWidget(self.btnInitGit)
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.formLayout.setItem(12, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(durraDialog)
        QtCore.QMetaObject.connectSlotsByName(durraDialog)

    def retranslateUi(self, durraDialog):
        _translate = QtCore.QCoreApplication.translate
        durraDialog.setWindowTitle(_translate("durraDialog", "DURRA"))
        self.lblFilename.setToolTip(_translate("durraDialog", "active Document filename"))
        self.lblFilename.setText(_translate("durraDialog", "<filename>"))
        self.lblTitle.setText(_translate("durraDialog", "Title"))
        self.txtTitle.setToolTip(_translate("durraDialog", "Document Info title"))
        self.lblEditingTimeLabel.setText(_translate("durraDialog", "Editing Time"))
        self.lblEditingTime.setToolTip(_translate("durraDialog", "Document Info editing-time"))
        self.lblEditingTime.setText(_translate("durraDialog", "<editing-time>"))
        self.lblAuthor.setText(_translate("durraDialog", "Author"))
        self.lblAuthorEmail.setText(_translate("durraDialog", "Author E-Mail"))
        self.lblLicense.setText(_translate("durraDialog", "License"))
        self.lblReversionLabel.setText(_translate("durraDialog", "Revision"))
        self.txtRevision.setToolTip(_translate("durraDialog", "Document Info editing-cycles"))
        self.lblKeyword.setText(_translate("durraDialog", "Keyword"))
        self.txtKeyword.setToolTip(_translate("durraDialog", "Document Info keyword; Use \';\' (Example: Linux;Master;Race)"))
        self.lblVersionLabel.setText(_translate("durraDialog", "Version"))
        self.lblVersion.setToolTip(_translate("durraDialog", "New Version"))
        self.lblVersion.setText(_translate("durraDialog", "<version>"))
        self.txtDescription.setToolTip(_translate("durraDialog", "Document Info abstract"))
        self.txtDescription.setPlaceholderText(_translate("durraDialog", "Description"))
        self.txtMessage.setPlaceholderText(_translate("durraDialog", "Commit Message"))
        self.txtLog.setToolTip(_translate("durraDialog", "Log"))
        self.txtLog.setPlaceholderText(_translate("durraDialog", "Log/Output"))
        self.groupBox_2.setTitle(_translate("durraDialog", "Commit/Versioning"))
        self.btnCommitMetaFiles.setToolTip(_translate("durraDialog", "<html><head/><body><p>generate only Meta-Files: TITLE, DESCRIPTION, KEYWORD, README.md, LICENSE and VERSION</p><p>and make a commit</p><p>(use this if you just want to commit the Meta-Files, not Images)</p><p><br/></p></body></html>"))
        self.btnCommitMetaFiles.setText(_translate("durraDialog", "Commit gen. Meta-&Files"))
        self.btnCommit.setToolTip(_translate("durraDialog", "<html><head/><body><p>save Document</p><p>generate Meta-Files: TITLE, DESCRIPTION, KEYWORD, README.md, LICENSE and VERSION and Images</p><p>make a git commit</p><p>(use this if your Document is still in WIP; if you have already &gt;=1.x.x version use the &quot;New ... Version&quot;-Buttons)</p><p><br/></p></body></html>"))
        self.btnCommit.setText(_translate("durraDialog", "Commit &WIP"))
        self.btnNewMajorVersion.setToolTip(_translate("durraDialog", "<html><head/><body><p>save Document, generate Meta-Files, update Major Version and make a git commit</p><p>(update Major Version if you already finished your Document and totally change stuff; New Version)</p></body></html>"))
        self.btnNewMajorVersion.setText(_translate("durraDialog", "New &Major Version"))
        self.btnNewMinjorVersion.setToolTip(_translate("durraDialog", "<html><head/><body><p>save Document, generate Meta-Files, update Minjor Version and make a git commit</p><p>(update Minjor Version if you already finished your Document and need to add/remove stuff)</p></body></html>"))
        self.btnNewMinjorVersion.setText(_translate("durraDialog", "&New Minjor Version"))
        self.btnNewPatchedVersion.setToolTip(_translate("durraDialog", "<html><head/><body><p>save Document, generate Meta-Files, update Patch/Revision Version and make a git commit</p><p>(update Revision Version if you already finished your Document and fixed just little stuff; nothing new added)</p></body></html>"))
        self.btnNewPatchedVersion.setText(_translate("durraDialog", "New &Patched Version"))
        self.groupBox.setTitle(_translate("durraDialog", "Save Files"))
        self.btnSave.setToolTip(_translate("durraDialog", "Save current Document"))
        self.btnSave.setText(_translate("durraDialog", "&Save Document"))
        self.btnGenFiles.setToolTip(_translate("durraDialog", "<html><head/><body><p>generate only Meta-Files: TITLE, DESCRIPTION, KEYWORD, README.md, LICENSE and VERSION</p></body></html>"))
        self.btnGenFiles.setText(_translate("durraDialog", "&Generate Meta-Files"))
        self.btnInitGit.setText(_translate("durraDialog", "init git..."))


